import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import Image from "next/image";
const MusicGrid = dynamic(() => import("../containers/MusicGrid"), {
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Music Maker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MusicGrid />
      <div className="absolute w-full h-[110px] bottom-0 border-t-[1px] border-solid border-t-gray"></div>
    </>
  );
};

export default Home;
